version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install numpy pytest
      - run:
          name: Install SciPy
          command: pip install scipy
      - run:
          name: List files
          command: ls -l
      - run:
          name: Run pythonfile
          command: |
            python sparse_recommender.py
      - run:
          name: Run PyTest
          command: |
            pytest test.py
      

  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build -t $tongsi/myapp:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "St!980730" | docker login --tongsi $tongsi --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $tongsi/myapp:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests
      - build_and_push:
          requires:
            - run_tests
          filters:
            branches:
              only: main
