version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install numpy pytest
      - run:
          name: Install SciPy
          command: pip install scipy
      - run:
          name: List files
          command: ls -l
      - run:
          name: Run pythonfile
          command:
            python sparse_recommender.py
      - run:
          name: Run PyTest
          command: 
            pytest test.py
      
      - setup_remote_docker:
          version: 19.03.13

  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Echo Docker Image Name
          command:
            echo "Docker Image Name:| $tongsi/myapp:latest"
      - run:
          name: Build Docker Image
          command: |
            
            docker build -t yourusername/myapp:latest .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "St!980730" | docker login --username $tong.si@slu.edu --password St!980730
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $tong.si@slu.edu/myapp:$latest 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests
      - build_and_push:
          requires:
            - run_tests
          filters:
            branches:
              only: main
