version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      

      - run:
          name: Build Docker Image
          command: |
            docker build -t $tongsi/my-python-app1:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$St!980730" | docker login --tongsi $tongsi --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $tongsi/my-python-app:${CIRCLE_SHA1} 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
            only:main
